name 'pginstall'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures pginstall'
long_description 'Installs/Configures pginstall'
version '0.1.0'
